[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "https://decetralizedrenderer.netlify.app/.netlify/functions/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = ":splat", Access-Control-Allow-Origin = "*" }

